version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  mysql:
    image: mariadb:10.11.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  adminer:
    container_name: recruitment-task-solution
    image: adminer
    restart: always
    ports:
      - '8080:8080'